lints.workspace = true

[package]
name = "netgauze-parse-utils"
version = "0.13.0"
edition = "2024"
authors = ["Ahmed Elhassany <a.hassany@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/NetGauze/NetGauze"
homepage = "https://netgauze.io"
description = """
Serialization/Deserialization utilities for NetGauze
"""
keywords = ["protocol"]
categories = ["parsing"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true  }
ipnet = { workspace = true }

[features]
test-helpers = []
