[package]
name = "netgauze-bgp-pkt"
version = "0.1.0"
edition = "2021"
authors = ["Ahmed Elhassany <a.hassany@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/NetGauze/NetGauze"
homepage = "https://github.com/NetGauze/NetGauze"
description = """
BGP-4 Protocol representation and serde.
"""
keywords = ["bgp", "parser", "protocol"]
categories = ["network-programming", "parsing"]

[dependencies]
netgauze-iana = { path = "../iana" }
netgauze-locate = { path = "../locate", optional = true }
netgauze-parse-utils = { path = "../parse-utils", optional = true }
netgauze-serde-macros = { path = "../serde-macros", optional = true }
ipnet = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }
nom = { workspace = true, optional = true }
byteorder = { workspace = true, optional = true }
criterion = { workspace = true, optional = true } # Dev dep for bench

[features]
default = ["serde"]
serde = ["nom", "byteorder", "netgauze-locate", "netgauze-parse-utils", "netgauze-serde-macros"]
bench = ["criterion"]


[dev-dependencies]
netgauze-parse-utils = { path = "../parse-utils", features = ["test-helpers"] }
serde_json = { workspace = true }


[[bench]]
name = "serde_benchmark"
harness = false
required-features = ["bench"]
